# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8756f7c18f4105426d917b3eae9935c344e097d6b927ef6faa4b3dade4f491c6e0c8098b66b722a3c8781c091ca801e386660c9cf91a0fa5477851db3275a2d3

test:
  secret_key_base: 649fd35a176b3b2452507be18fcf759808eb563388f56abc9c15bb53434c4cb759432dc756f7cce7692db85a0b5fda686148ae9a217d77c209f3cda65129a3a0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
